"""The curl installer's optional global launcher (scripts/install_macos.sh).

The script used to `cp` its launcher over /opt/homebrew/bin/mtplx by default.
That path is Homebrew's symlink into its Cellar, so the copy overwrote
Homebrew's program, and in the other order `brew install` could not link
(C-04). These tests source the script's functions with the
MTPLX_INSTALLER_SOURCE_ONLY hook and drive `install_global_launcher` against
a scratch prefix tree; nothing is installed.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "install_macos.sh"
MARKER = "MTPLX launcher. Generated by scripts/install_macos.sh."


def _run_install_global_launcher(launcher: Path, global_bin: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            "bash",
            "-c",
            'MTPLX_INSTALLER_SOURCE_ONLY=1 source "$0" && install_global_launcher "$1" "$2"',
            str(SCRIPT),
            str(launcher),
            str(global_bin),
        ],
        text=True,
        capture_output=True,
        check=False,
    )


@pytest.fixture
def launcher(tmp_path: Path) -> Path:
    user_bin = tmp_path / "home" / ".local" / "bin"
    user_bin.mkdir(parents=True)
    path = user_bin / "mtplx"
    path.write_text(f"#!/usr/bin/env bash\n# {MARKER}\nexec /nowhere/venv/bin/mtplx \"$@\"\n")
    path.chmod(0o755)
    return path


def _fake_homebrew(tmp_path: Path) -> tuple[Path, Path]:
    """A Homebrew prefix whose bin/mtplx is a symlink into the Cellar."""
    prefix = tmp_path / "homebrew"
    cellar_bin = prefix / "Cellar" / "mtplx" / "2.7.1" / "bin"
    cellar_bin.mkdir(parents=True)
    brew_program = cellar_bin / "mtplx"
    brew_program.write_text("#!/bin/bash\nexec /opt/homebrew/Cellar/mtplx/2.7.1/libexec/bin/mtplx\n")
    brew_program.chmod(0o755)
    (prefix / "bin").mkdir()
    (prefix / "bin" / "mtplx").symlink_to(Path("..") / "Cellar" / "mtplx" / "2.7.1" / "bin" / "mtplx")
    return prefix, brew_program


def test_script_parses():
    result = subprocess.run(["bash", "-n", str(SCRIPT)], text=True, capture_output=True)
    assert result.returncode == 0, result.stderr


def test_source_only_hook_defines_functions_without_installing(tmp_path):
    result = subprocess.run(
        ["bash", "-c", 'MTPLX_INSTALLER_SOURCE_ONLY=1 source "$0" && type install_global_launcher', str(SCRIPT)],
        text=True,
        capture_output=True,
        env={**os.environ, "HOME": str(tmp_path)},
    )
    assert result.returncode == 0, result.stderr
    assert "install_global_launcher is a function" in result.stdout
    assert not (tmp_path / ".mtplx").exists()


def test_refuses_to_replace_homebrew_symlink(tmp_path, launcher):
    prefix, brew_program = _fake_homebrew(tmp_path)
    before = brew_program.read_text()

    result = _run_install_global_launcher(launcher, prefix / "bin")

    assert result.returncode == 1
    assert "Skipped the global launcher" in result.stdout
    assert "was not created by this installer" in result.stdout
    assert "may belong to Homebrew" in result.stdout
    assert str(launcher) in result.stdout
    # Homebrew's program and its link are untouched.
    link = prefix / "bin" / "mtplx"
    assert link.is_symlink()
    assert os.readlink(link) == "../Cellar/mtplx/2.7.1/bin/mtplx"
    assert brew_program.read_text() == before


def test_refuses_a_foreign_regular_file(tmp_path, launcher):
    global_bin = tmp_path / "usr-local-bin"
    global_bin.mkdir()
    foreign = global_bin / "mtplx"
    foreign.write_text("#!/bin/sh\necho someone else's mtplx\n")

    result = _run_install_global_launcher(launcher, global_bin)

    assert result.returncode == 1
    assert "Skipped the global launcher" in result.stdout
    assert not foreign.is_symlink()
    assert foreign.read_text() == "#!/bin/sh\necho someone else's mtplx\n"


def test_links_into_an_empty_directory_and_is_idempotent(tmp_path, launcher):
    global_bin = tmp_path / "global-bin"
    global_bin.mkdir()

    result = _run_install_global_launcher(launcher, global_bin)

    assert result.returncode == 0, result.stdout + result.stderr
    assert result.stdout == ""
    target = global_bin / "mtplx"
    assert target.is_symlink()
    assert os.readlink(target) == str(launcher)

    again = _run_install_global_launcher(launcher, global_bin)
    assert again.returncode == 0
    assert os.readlink(target) == str(launcher)


def test_replaces_a_launcher_copied_by_an_earlier_run(tmp_path, launcher):
    """Earlier versions copied the launcher (a regular file carrying the
    marker). That copy is ours and becomes a link."""
    global_bin = tmp_path / "global-bin"
    global_bin.mkdir()
    old_copy = global_bin / "mtplx"
    old_copy.write_text(launcher.read_text())
    old_copy.chmod(0o755)

    result = _run_install_global_launcher(launcher, global_bin)

    assert result.returncode == 0, result.stdout + result.stderr
    assert old_copy.is_symlink()
    assert os.readlink(old_copy) == str(launcher)


def test_unwritable_directory_is_reported_plainly(tmp_path, launcher):
    if os.geteuid() == 0:
        pytest.skip("root can write anywhere")
    global_bin = tmp_path / "locked-bin"
    global_bin.mkdir()
    global_bin.chmod(0o555)
    try:
        result = _run_install_global_launcher(launcher, global_bin)
    finally:
        global_bin.chmod(0o755)

    assert result.returncode == 1
    assert "could not write to" in result.stdout
    assert str(launcher) in result.stdout


def test_default_flow_never_targets_a_homebrew_prefix():
    """The script must not choose /opt/homebrew/bin or /usr/local/bin on its
    own; a global launcher exists only when MTPLX_GLOBAL_BIN is set."""
    text = SCRIPT.read_text()
    assert 'global_bin="/opt/homebrew/bin"' not in text
    assert 'global_bin="/usr/local/bin"' not in text
    assert 'cp "$launcher"' not in text
    assert 'install_global_launcher "$launcher" "$MTPLX_GLOBAL_BIN"' in text
