#!/usr/bin/env bash
set -euo pipefail

# First comment line of every launcher this script writes; the global-launcher
# step uses it to recognise its own work.
launcher_marker="MTPLX launcher. Generated by scripts/install_macos.sh."

usage() {
  cat <<'EOF'
Usage:
  curl -fsSL https://raw.githubusercontent.com/youssofal/MTPLX/main/scripts/install_macos.sh | bash

Installs MTPLX from PyPI into ~/.mtplx/venv and creates a durable `mtplx`
launcher in ~/.local/bin. It never writes into Homebrew's directories; set
MTPLX_GLOBAL_BIN to also link the launcher from a directory of your choice.

Environment:
  MTPLX_PACKAGE_SPEC=mtplx              Package spec to install, for example mtplx==0.1.4
  MTPLX_PYTHON=/path/to/python3         Python interpreter override
  MTPLX_VENV=~/.mtplx/venv              Install venv path
  MTPLX_USER_BIN=~/.local/bin           User launcher directory
  MTPLX_GLOBAL_BIN=/some/dir            Optional: also link the launcher as /some/dir/mtplx
  MTPLX_SKIP_GLOBAL_LAUNCHER=1          Ignore MTPLX_GLOBAL_BIN
EOF
}

# Link "$2/mtplx" to the launcher "$1". Only a link or file this script created
# (recognised by its marker comment) is replaced: Homebrew's mtplx lives at the
# same name as a symlink into its Cellar, and copying over it overwrote
# Homebrew's program while a later `brew install` could no longer link.
# Returns 0 when the link is in place, 1 when it was skipped (with the reason
# printed).
install_global_launcher() {
  local launcher="$1"
  local global_bin="$2"
  local target="$global_bin/mtplx"

  if [ -L "$target" ] && [ "$(readlink "$target")" = "$launcher" ]; then
    return 0
  fi
  if [ -e "$target" ] || [ -L "$target" ]; then
    if ! head -c 512 "$target" 2>/dev/null | grep -q "$launcher_marker"; then
      echo "Skipped the global launcher: $target already exists and was not created by this installer (it may belong to Homebrew)."
      echo "MTPLX is available as $launcher. To replace $target, remove it first and rerun."
      return 1
    fi
  fi
  if ln -sfn "$launcher" "$target" 2>/dev/null; then
    return 0
  fi
  echo "Skipped the global launcher: could not write to $global_bin (permission denied)."
  echo "MTPLX is available as $launcher. Point MTPLX_GLOBAL_BIN at a directory you can write to, or leave it unset."
  return 1
}

# Test hook: `MTPLX_INSTALLER_SOURCE_ONLY=1 source install_macos.sh` defines the
# functions above without installing anything.
if [ "${MTPLX_INSTALLER_SOURCE_ONLY:-0}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

if [ "$(uname -s)" != "Darwin" ] || [ "$(uname -m)" != "arm64" ]; then
  echo "error: this installer is for Apple Silicon Macs." >&2
  echo "MTPLX depends on MLX and is not a Windows/Linux/Intel Mac package." >&2
  exit 2
fi

package_spec="${MTPLX_PACKAGE_SPEC:-mtplx}"
venv="${MTPLX_VENV:-$HOME/.mtplx/venv}"
user_bin="${MTPLX_USER_BIN:-$HOME/.local/bin}"
launcher="$user_bin/mtplx"
python_bin="${MTPLX_PYTHON:-}"

if [ -z "$python_bin" ]; then
  candidates=(
    /opt/homebrew/bin/python3.14
    /opt/homebrew/bin/python3.13
    /opt/homebrew/bin/python3.12
    /opt/homebrew/bin/python3.11
    /opt/homebrew/bin/python3
    /usr/local/bin/python3.14
    /usr/local/bin/python3.13
    /usr/local/bin/python3.12
    /usr/local/bin/python3.11
    /usr/local/bin/python3
    python3.14
    python3.13
    python3.12
    python3.11
    python3
  )
  for candidate in "${candidates[@]}"; do
    if [ -x "$candidate" ]; then
      python_bin="$candidate"
      break
    elif command -v "$candidate" >/dev/null 2>&1; then
      python_bin="$(command -v "$candidate")"
      break
    fi
  done
fi

if [ -z "$python_bin" ]; then
  echo "error: could not find Python 3.11+." >&2
  echo "Checked Homebrew paths (/opt/homebrew/bin, /usr/local/bin) and PATH." >&2
  echo "Install Python 3.11+ first, then rerun this installer." >&2
  exit 2
fi

"$python_bin" - <<'PY'
import sys

if sys.version_info < (3, 11):
    print(
        f"error: MTPLX needs Python 3.11+, found {sys.version.split()[0]}",
        file=sys.stderr,
    )
    raise SystemExit(2)
PY

echo "Using Python: $python_bin"
echo "Installing:   $package_spec"
echo "Venv:         $venv"

"$python_bin" -m venv "$venv"
"$venv/bin/python" -m pip install -U pip
"$venv/bin/python" -m pip install -U "$package_spec"

mkdir -p "$user_bin"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# $launcher_marker
set -e

if [ -z "\${HF_HOME:-}" ] && [ -d "\$HOME/.cache/huggingface-mtplx" ]; then
  export HF_HOME="\$HOME/.cache/huggingface-mtplx"
fi

exec "$venv/bin/mtplx" "\$@"
EOF
chmod 755 "$launcher"

path_snippet="
# MTPLX CLI
case \":\$PATH:\" in
  *\":$user_bin:\"*) ;;
  *) export PATH=\"$user_bin:\$PATH\" ;;
esac
"

for rcfile in "$HOME/.zprofile" "$HOME/.zshrc" "$HOME/.bash_profile"; do
  touch "$rcfile"
  if ! grep -q 'MTPLX CLI' "$rcfile"; then
    printf '%s\n' "$path_snippet" >> "$rcfile"
  fi
done

# A global launcher is opt-in. Homebrew's own /opt/homebrew/bin and
# /usr/local/bin are never chosen by default: the launcher in ~/.local/bin is
# the install, and the PATH snippet above makes it reachable.
global_launcher=""
if [ -n "${MTPLX_GLOBAL_BIN:-}" ] && [ "${MTPLX_SKIP_GLOBAL_LAUNCHER:-0}" != "1" ]; then
  if install_global_launcher "$launcher" "$MTPLX_GLOBAL_BIN"; then
    global_launcher="$MTPLX_GLOBAL_BIN/mtplx"
  fi
fi

"$launcher" --version
"$launcher" help >/dev/null

echo
echo "MTPLX installed:"
echo "  $launcher"
if [ -n "$global_launcher" ]; then
  echo "  $global_launcher"
fi
echo
echo "Open a new Terminal tab, or run:"
echo "  export PATH=\"$user_bin:\$PATH\""
echo
echo "Then start MTPLX:"
echo "  mtplx start"
